### ISSUE TITLE
Destiny Item Manager not loading UI

### ISSUE THREAD

**Issue by xgenosis** [dynamiquel/GameBarBrowser#24]
DIM - allows me to sign in and authenticate with steam and bungie but then sits on an infinite loading screen trying to pull the inventory. I saw this tweet https://twitter.com/thisisdim/status/1262092194581708800?lang=en where the guys had it working but when I asked them about it they weren't able to provide any support. Can this please be looked into?

**Comment by dynamiquel** [comment]
I've done a quick look into it. I believe DIM no longer supports the old Microsoft Edge (or at least the version that Windows 10 apps use). I traced the update history but didn't seem to find any mention of it.

**Comment by xgenosis** [comment]
ah bugger, so nothing that can be done about it at this stage then?

**Comment by dynamiquel** [comment]
Not really. Game Bar should eventually support the new version of Edge (Chromium) in the future.
