### ISSUE TITLE
Edge extensions

### ISSUE THREAD

**Issue by LoneFenris** [dynamiquel/GameBarBrowser#33]
I'm not sure if this is possible within the UWP framework (I'm guessing not, but I figured I'd ask), but it would be cool if this browser was also able to draw from installed Edge extensions like uBlock and others.

**Comment by dynamiquel** [comment]
I do not believe it is possible to use Edge extensions in UWP. However, it should be possible to create some form of ad-block by executing Javascript code straight into the website, likely with the help of some public ad-block API - if they exist. All of this is outside my comfort zone unfortunately.
